title: Freifunk Düsseldorf
baseURL: /
params:
  color_scheme: light
  accent_color: pink
  header:
    title: Freifunk Düsseldorf
    has_nav: true
    logo_img: /images/freifunk-ddorf-229c545d.svg
  footer:
    content: Freifunk Düsseldorf e.V.
    links:
      - new_window: false
        text: Impressum
        url: /impressum/
      - new_window: false
        text: Pico Peering Agreement
        url: /ppa/
      - new_window: true
        text: Status
        url: https://status.freifunk-duesseldorf.de/
    has_social: true
menu:
  main: []
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
