title: Freifunk Düsseldorf
baseURL: /
params:
  color_scheme: light
  accent_color: pink
  header:
    title: Freifunk Düsseldorf
    has_nav: true
    logo_img: /images/freifunk-ddorf-229c545d.svg
  footer:
    content: Freifunk Düsseldorf e.V.
    links: []
    has_social: true
menu:
  main:
    - name: Start
      url: /
      identifier: start
    - identifier: kontakt
      name: Kontakt
      url: /contact/
    - identifier: anleitung
      name: Anleitung
      url: /anleitung/
    - identifier: news
      name: News
      url: /blog/
    - identifier: verein
      name: Verein
      url: /verein/
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
