[build]
publish = "public"
command = "hugo"

  [build.environment]
  HUGO_VERSION = "0.105.0"

[[redirects]]
  from = "/download"
  to = "https://firmware.freifunk-duesseldorf.de/"
  status = 301

[[redirects]]
  from = "/kontakt"
  to = "/contact"
  status = 301

[[headers]]
  for = "/*"

  [headers.values]
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
